mode: development
media_root:: media
media_url: /media
base_url: /
template: hyde.ext.templates.jinja.Jinja2Template
plugins:
    - hyde.ext.plugins.meta.MetaPlugin
    - hyde.ext.plugins.auto_extend.AutoExtendPlugin
    - hyde.ext.plugins.less.LessCSSPlugin
    - hyde.ext.plugins.blockdown.BlockdownPlugin
    - hyde.ext.plugins.sorter.SorterPlugin
    - hyde.ext.plugins.grouper.GrouperPlugin
    - hyde.ext.plugins.markings.MarkingsPlugin
    - hyde.ext.plugins.markings.ReferencePlugin
    - hyde.ext.plugins.syntext.SyntextPlugin
    - hyde.ext.plugins.textlinks.TextlinksPlugin
context:
    data:
        version: 0.8
        basic_template:
            base:
                http://emberapp.com/lakshmivyas/images/
            images:
                -
                    name: hyde-basic-home
                    description: The home page
                -
                    name: hyde-basic-list
                    description: List of blog posts
                -
                    name: hyde-basic-blog-post
                    description: A blog post
                -
                    name: hyde-basic-tag-list
                    description: List of blogs posts with a specific tag
    providers:
        links: links.yaml
meta:
    extends: doc.j2
    default_block: doc
    nodemeta: meta.yaml
    toc: root
    index: -1
    charset: utf-8
    compatibility: 'IE=edge,chrome=1'
    viewport: 'width=device-width, initial-scale=1.0'
    description: >
        Awesome documentation for hyde -
        a python static website generator
    title: Hyde - A Python Static Website Generator
    keywords: >
                hyde,python,django,jinja,static website,static site,
                generator,html generator
    author: Lakshmi Vyasarajan
sorter:
    index:
        attr:
            - meta.index
        filters:
            source_file.kind: html
grouper:
    toc:
        sorter: index
        hide_name: True
        groups:
            -
                name: root
                hide_name: True
                groups:
                    -
                        name: getting started
                    -
                        name: templating guide

less:
    app: /usr/bin/lessc
markdown:
    extensions:
        - def_list
        - headerid
publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: ../hyde.github.com
        url: git@github.com:hyde/hyde.github.com.git
